name: ETL

on:
  workflow_call:
    inputs:
      sport_key:
        required: true
        type: string

permissions:
  contents: read
  id-token: write

jobs:
  etl:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: google-github-actions/auth@v1
        with:
          workload_identity_provider: projects/108686647178/locations/global/workloadIdentityPools/github-the-odds-api/providers/github
          service_account: github-the-odds-api@matheusccouto.iam.gserviceaccount.com

      - uses: google-github-actions/setup-gcloud@v1

      - id: timestamp
        name: Timestamp
        run: |
          TIMESTAMP=$(date +%s)
          echo timestamp=$TIMESTAMP >> $GITHUB_OUTPUT      

      - name: Extract from API
        run: curl -s "https://api.the-odds-api.com/v4/sports/${{ inputs.sport_key }}/odds?apiKey=${{ secrets.THE_ODDS_API_KEY }}?regions=eu&markets=h2h" | jq -cr '.[]' > data.json
      
      - name: Load to Google Cloud Storage
        run: gcloud storage cp data.json gs://the-odds-api/${{ inputs.sport_key }}/${{ steps.timestamp.outputs.timestamp }}.json

      - name: Load to Google BigQuery from Google Cloud Storage
        run: |
          bq load \
            --source_format=NEWLINE_DELIMITED_JSON \
            --autodetect \
            the_odds_api.odds \
            gs://the-odds-api/${{ inputs.sport_key }}/${{ steps.extract.outputs.timestamp }}.json