name: Keep repo alive

on:
  schedule:
    - cron: "0 0 * * 0"

jobs:
  keepalive:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: gautamkrishnar/keepalive-workflow@v1
