name: Endpoints

on:
  push:
    branches:
      - main

permissions:
  contents: read
  id-token: write

jobs:
  etl:
    uses: ./.github/workflows/etl.yml
    name: soccer_brazil_campeonato
    with:
      sport_key: soccer_brazil_campeonato
    secrets: inherit
